# Generated by Django 3.0.5 on 2020-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('send_time', models.DateTimeField(verbose_name='send time')),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
